[build]
  base = "GXReservationClient"       # Netlify will cd into this folder
  command = "npm install && npm run build"
  publish = "dist/gxreservation-client"  # Now relative to base directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
   force = true 